
package com.ss.conversorMultiple.GUI;

import com.ss.conversorMultiple.GUI.errors.CurrencyError;
import com.ss.conversorMultiple.GUI.errors.QuantityError;
import com.ss.conversorMultiple.Logica.Currency;


public class CurrencyMenu extends javax.swing.JFrame {

    /**
     * Creates new form CurrencyMenu
     */
    public CurrencyMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        currencyConvertTitle = new javax.swing.JLabel();
        selectLabel1 = new javax.swing.JLabel();
        currencyCombo1 = new javax.swing.JComboBox<>();
        aceptButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        currencyCombo2 = new javax.swing.JComboBox<>();
        selectLabel2 = new javax.swing.JLabel();
        convertCurrency = new javax.swing.JTextField();
        dataTextLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantityInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setSize(new java.awt.Dimension(600, 400));

        currencyConvertTitle.setFont(new java.awt.Font("Chakra Petch", 1, 36)); // NOI18N
        currencyConvertTitle.setText("Conversor de Moneda");

        selectLabel1.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        selectLabel1.setText("Seleccione una moneda");

        currencyCombo1.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        currencyCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "USD", "Euros", "Yenes Japones", "Pesos" }));
        currencyCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyCombo1ActionPerformed(evt);
            }
        });

        aceptButton.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        aceptButton.setText("Aceptar");
        aceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptButtonActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        currencyCombo2.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N

        selectLabel2.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        selectLabel2.setText("Seleccione una moneda");

        convertCurrency.setEditable(false);
        convertCurrency.setFont(new java.awt.Font("Chakra Petch", 1, 24)); // NOI18N
        convertCurrency.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        convertCurrency.setText("0");

        dataTextLabel.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        dataTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dataTextLabel.setText(" ");

        quantityLabel.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        quantityLabel.setText("Cantidad a convertir");

        quantityInput.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        quantityInput.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityInput.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(currencyCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(selectLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(currencyCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addGap(38, 38, 38)
                .addComponent(aceptButton)
                .addGap(198, 198, 198))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(currencyConvertTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(convertCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(dataTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(currencyConvertTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectLabel1)
                    .addComponent(currencyCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectLabel2)
                            .addComponent(currencyCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(dataTextLabel)
                .addGap(18, 18, 18)
                .addComponent(convertCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptButton)
                    .addComponent(jButton3))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void aceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptButtonActionPerformed
        float quantity = Float.parseFloat(quantityInput.getText());
        String currency1 = String.valueOf(currencyCombo1.getSelectedItem());
        String currency2 = String.valueOf(currencyCombo2.getSelectedItem());

        if(currency1.compareTo("Seleccione") == 0 || currency2.isEmpty() ){

            CurrencyError error = new CurrencyError();
            error.setVisible(true);
            error.setLocationRelativeTo(null);
            error.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        }else if(quantity == 0.00){

            QuantityError error = new QuantityError();
            error.setVisible(true);
            error.setLocationRelativeTo(null);
            error.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        }else{

            Currency currency = new Currency(currency1, currency2, quantity);

            String result = String.valueOf(currency.converter());

            StringBuilder sb = new StringBuilder();

            sb.append(quantity)
            .append(" ")
            .append(currency1)
            .append(" son equivalentes a ")
            .append(currency2);

            dataTextLabel.setText(sb.toString());

            convertCurrency.setText(result);
        }
    }//GEN-LAST:event_aceptButtonActionPerformed

    private void currencyCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyCombo1ActionPerformed
        String item = String.valueOf(currencyCombo1.getSelectedItem());

        if(item.compareTo("Pesos") == 0){
            currencyCombo2.removeAllItems();
            currencyCombo2.addItem("USD");
            currencyCombo2.addItem("Euros");
            currencyCombo2.addItem("Yenes Japoneses");
        }else if(item.compareTo("Seleccione") != 0){
            currencyCombo2.removeAllItems();
            currencyCombo2.addItem("Pesos");

        }else{
            currencyCombo2.removeAllItems();
        }

    }//GEN-LAST:event_currencyCombo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptButton;
    private javax.swing.JTextField convertCurrency;
    private javax.swing.JComboBox<String> currencyCombo1;
    private javax.swing.JComboBox<String> currencyCombo2;
    private javax.swing.JLabel currencyConvertTitle;
    private javax.swing.JLabel dataTextLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField quantityInput;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel selectLabel1;
    private javax.swing.JLabel selectLabel2;
    // End of variables declaration//GEN-END:variables
}
